# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: online_pooja
  username: postgres
  password: anshul
  host: localhost
  port: 5433

test:
  <<: *default
  database: online_pooja_test
  username: postgres
  password: anshul
  host: localhost
  port: 5433

# 🔹 For Render (Production)
production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
